server:
  port: 8102

spring:
  dubbo: 
    application:
      name: auth-consumer
    registry: 
      address: zookeeper://127.0.0.1:2181
    protocol:
      name: dubbo
    scan: com.wll.dubbo.controller
    qos:
      port: 22223
    consumer: 
      check: false